name: Build and test CredentialManagement
on:
  push:
    branches:
    - development
  pull_request:
    branches:
    - development
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - run: dotnet restore "src\CredentialManagement\CredentialManagement.csproj"
    - run: dotnet build "src\CredentialManagement\CredentialManagement.csproj" --configuration Release
    - run: dotnet test "src\CredentialManagement.Test\CredentialManagement.Test.csproj" --configuration Release --no-build    
